### ISSUE TITLE
VERY bad news...

### ISSUE THREAD

**Issue by TrickJoker312** [Realhack1/Realhacks-Unblocked-Games-links#12]
So... My school blocked the github.io links.
They may be blocking github next.
:(
what exactly do I do?

**Comment by McProgrammerX** [comment]
umm what

**Comment by McProgrammerX** [comment]
javascript:(function(){var destination = prompt("Destination (Don't include http/https: ");window.location='https://translate.google.com/translate?sl=auto&tl=en&u=%27+%27https://%27+destination})();

Add this to ur bookmarks and this may work just add the GitHub IO links without the http:// or https:// OK?

**Comment by McProgrammerX** [comment]
The source of the code was from here give them credit:
https://gist.github.com/i0Z3R0/25b0c165d6b2eff78fa9d4c0aba9cd26

**Comment by TrickJoker312** [comment]
👍

**Comment by McProgrammerX** [comment]
Hope it works for you

**Comment by Realhack1** [comment]
Work around put a proxy link in a doc then click the profile and log in on the proxie
