### ISSUE TITLE
GROUP TO STOP REALHACK1

### ISSUE THREAD

**Issue by SuperLexer9** [Realhack1/Realhacks-Unblocked-Games-links#21]
We need to stop this dude from shutting down GitHub

**Comment by SuperLexer9** [comment]
with his hacks

**Comment by Realhack1** [comment]
why would i hack github? my repo is here and i make 200 dollars a week from it

**Comment by SuperLexer9** [comment]
But ur a hacker

**Comment by Realhack1** [comment]
Would you report tubers93 if he hacked you

**Comment by SuperLexer9** [comment]
I would not report him I'll report you

**Comment by SuperLexer9** [comment]
Leave GitHub before I send a report to GitHub

**Comment by SuperLexer9** [comment]
And I will cause you more trouble

**Comment by Realhack1** [comment]
im a hacker duh but if i make 200 dollars a week  from github i would i boot github?

**Comment by Realhack1** [comment]
why would i boot github github pays me
