### ISSUE TITLE
U suck

### ISSUE THREAD

**Issue by SuperLexer9** [Realhack1/Realhacks-Unblocked-Games-links#22]
U suck

**Comment by Realhack1** [comment]
cringe

**Comment by Realhack1** [comment]
yall worship a discord mod

**Comment by Notyourgames** [comment]
yo where can i contact you I also got hacked  by him

**Comment by SuperLexer9** [comment]
Hey stupid Realhack1

**Comment by SuperLexer9** [comment]
why are you talking about Tubers93

**Comment by SuperLexer9** [comment]
I HATE YOU REALHACK1. Go: 😭 ⏩👊😱😭

that means you go cry then you get beaten up then you get shocked and cry

**Comment by Realhack1** [comment]
CRINGE

**Comment by SuperLexer9** [comment]
Ur more cringe

**Comment by Notyourgames** [comment]
hello can you help me Superlexer

**Comment by SuperLexer9** [comment]
yes
